### ISSUE TITLE
Plan to release data generation code

### ISSUE THREAD

**Issue by Jialuo-Li** [val-iisc/Reflecting-Reality#2]
Hi @cs-mshah,

Great work on this project! I truly appreciate your efforts and the insights it offers. I'm particularly interested in the dataset you generated and was wondering if you have any plans to release the code used for its creation.

It would mean a lot if you could share your plans or provide some details regarding this. Looking forward to your reply!

**Comment by cs-mshah** [comment]
Hi @Jialuo-Li 
I'm happy that you found our work interesting. Yes, the dataset generation code is also a major part of the project. I'll release the code for it in January as soon as I get some more time. In the meantime, you can have a look at our dataset on huggingface and some tutorials on blenderproc to get some idea on the generation pipeline.

**Comment by Jialuo-Li** [comment]
Thank you so much. Looking forward to the code release in January—thanks again!
